### ISSUE TITLE
Crook functions as a hoe

### ISSUE THREAD

**Issue by J3fftw1** [TheBusyBiscuit/SlimyTreeTaps#11]
## Description (Required)
The crook can be used to change dirt to farmland

## Steps to reproduce the Issue (Required)
get a crook
right click dirt
observe it 

## Expected behavior (Required)
Not to function as a hoe

## Server Log / Error Report
N/A

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: 90
 - Slimefun Version: 689
 - SlimyTreeTaps Version: 14

**Comment by TheBusyBiscuit** [comment]
There is no such thing as a crook in this addon...??

**Comment by J3fftw1** [comment]
wrong addon
